# Smith Waterman Algorithm

In [5]:
import itertools
import numpy as np

In [6]:
a = 'CGTGAATTCAT'
b = 'GACTTAC'

Scoring matrix =

$H_{ij} = max(H_{i-1, j-1} + s(a_1,b_j), 
              max_{k>=1}[H_{i-kj} - W_k])$

In [7]:
## Scoring Schema
def score(a,b):
    if a == b:
        return 1
    else:
        return -1
## Penalty gap (you set the score)
W = -8

In [8]:
## First step, initialize a matrix of dimensions (len(b)+1, len(a) + 1)
M = np.zeros((len(a) + 1, len(b) + 1), np.int)
M

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
## Substitution matrix 
    # Match = 1
    # mismatch = -1
S = np.zeros((len(a) + 1, len(b) + 1), np.int)

for i in range(len(a)):
    for j in range(len(b)):
        S[i,j] = 

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
range(len(a))

range(0, 11)

In [20]:
a = 'h'
b = 'h'
score(a,b)

1

In [31]:
## Second Step: filling the matrix (using the assumed scoring schema and initial values)
M[1,1] = max(M[0,0] + score(a[1], b[1]), H[0,0] - )

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
score(a[1], b[1])

0